version: 1
build:
  binary: karund
accounts:
- name: main
  coins:
  - 10000000000000000kar
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: kar
    evm:
      params:
        evm_denom: kar
    gov:
      deposit_params:
        min_deposit:
        - amount: "1000000"
          denom: kar
    mint:
      params:
        mint_denom: kar
    staking:
      params:
        bond_denom: kar
  chain_id: karun-testnet
validators:
- name: main
  bonded: 100000000000kar
  home: $HOME/.karund